apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all resources to
namespace: rs-movie-dev-ns

resources:
- config.yaml
- gateway.yaml
- ./efs/pv-claim.yaml
- ../../loader
- ../../filter
- ../../portrait
- ../../rank
- ../../recall
- ../../redis
- ../../event
- ../../retrieve
- ../../demo
- ui

# all with following *kustomization*
images:
- name: rs/demo
  newName: public.ecr.aws/t8u1z3c8/rs/demo
  newTag: latest
- name: rs/event
  newName: public.ecr.aws/t8u1z3c8/rs/event
  newTag: latest
- name: rs/filter
  newName: 521105912180.dkr.ecr.ap-northeast-1.amazonaws.com/rs/filter
  newTag: 2679c1883d435ff4cb18b3805814803f13a4fdff
- name: rs/filter-plugin
  newName: 521105912180.dkr.ecr.ap-northeast-1.amazonaws.com/rs/filter-plugin
  newTag: movie-2679c1883d435ff4cb18b3805814803f13a4fdff
- name: rs/loader
  newName: public.ecr.aws/t8u1z3c8/rs/loader
  newTag: latest
- name: rs/portrait
  newName: 521105912180.dkr.ecr.ap-northeast-1.amazonaws.com/rs/portrait
  newTag: 2679c1883d435ff4cb18b3805814803f13a4fdff
- name: rs/portrait-plugin
  newName: 521105912180.dkr.ecr.ap-northeast-1.amazonaws.com/rs/portrait-plugin
  newTag: movie-2679c1883d435ff4cb18b3805814803f13a4fdff
- name: rs/rank
  newName: 521105912180.dkr.ecr.ap-northeast-1.amazonaws.com/rs/rank
  newTag: 2679c1883d435ff4cb18b3805814803f13a4fdff
- name: rs/rank-plugin
  newName: 521105912180.dkr.ecr.ap-northeast-1.amazonaws.com/rs/rank-plugin
  newTag: movie-2679c1883d435ff4cb18b3805814803f13a4fdff
- name: rs/recall
  newName: 521105912180.dkr.ecr.ap-northeast-1.amazonaws.com/rs/recall
  newTag: 2679c1883d435ff4cb18b3805814803f13a4fdff
- name: rs/recall-plugin
  newName: 521105912180.dkr.ecr.ap-northeast-1.amazonaws.com/rs/recall-plugin
  newTag: movie-2679c1883d435ff4cb18b3805814803f13a4fdff
- name: rs/retrieve
  newName: public.ecr.aws/t8u1z3c8/rs/retrieve
  newTag: latest
- name: rs/ui
  newName: public.ecr.aws/t8u1z3c8/rs/ui
  newTag: latest



vars:
- fieldref:
    fieldPath: data.redis_host
  name: REDIS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.redis_port
  name: REDIS_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.messge_broker_redis_host
  name: MESSGE_BROKER_REDIS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.messge_broker_redis_port
  name: MESSGE_BROKER_REDIS_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.aws_region
  name: AWS_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.s3_bucket
  name: S3_BUCKET
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.s3_prefix
  name: S3_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.click_record_bucket
  name: CLICK_RECORD_BUCKET
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.click_record_file_path
  name: CLICK_RECORD_FILE_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.user_record_file_path
  name: USER_RECORD_FILE_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
- fieldref:
    fieldPath: data.local_data_folder
  name: LOCAL_DATA_FOLDER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-movie-dev-config
